name: My first workflow # telling what would be the job NAME , it will be shown under action TAB
on: [push] # triggering on which event this job going to run

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      # step: 1
      - name: Checkout my REPO first
        uses: actions/checkout@v4

      - name: List Out All The Files
        run: |
          echo "MY FIRST GITHUB ACTIONS JOB"
          ls -ltra
          cat README.md
      - name: second job to do
        run: |
          echo "It is time to do experiment"
