name: GENERATE ASCII OF DRAGON
on: push
jobs:
  generate-ascii-dragon:
    runs-on: ubuntu-latest
    steps:
      - name: check out the repo first
        run: actions/checkout@v7

      - name: Install cowsay
        run: sudo apt install cowsay -y

      - name: EXECUTE COWSAY CMD
        run: cowsay -f dragon "Run otherwise i am gonna burn you by my fire cause i'm dragon isn't it" >>  dragon.txt

      - name: Test File Exists or Not
        run: grep -i "dragon" dragon.txt

      - name: Read File
        run: cat dragon.txt

      - name: List Repo Files
        run: ls -ltra
