name: GENERATE ASCII OF DRAGON
on: push
jobs:
  generate-ascii-dragon:
    runs-on: ubuntu-latest
    steps:
      - name: check out the repo first
        uses: actions/checkout@v7

      - name: List Repo Files
        run: ls -ltra

      - name: Executing Shell Script
        run: |
          chmod u+x ascii-script.sh
          ./ascii-script.sh
