name: Exploring Variables and Secrets

on: push

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Docker Build
        env:
          DOCKER_REGISTRY: docker.io
          DOCKER_USERNAME: sumanta601
          DOCKER_IMAGE_NAME: github-actions-nginx
        run: docker build -t ${{env.DOCKER_REGISTRY}}/${{env.DOCKER_USERNAME}}/${{env.DOCKER_IMAGE_NAME}}:latest

      - name: Docker Login
        env:
          DOCKER_USERNAME: sumanta601
          DOCKER_PASSWORD: bleachIchigo
        run: docker login --username=$DOCKER_USERNAME--password=$DOCKER_PASSWORD

  deploy:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Docker Run
        run: docker run -d -p 8080:80 docker.io/sumanta601/imageName:latest
